version: "3.1"
services:
        postgres:
                image: postgres:13.5
                container_name: postgres
                working_dir: /app
                volumes:
                        - .:/app
                        - postgresdata:/var/lib/postgresql/data
                environment:
                        - POSTGRES_USER=root
                        - POSTGRES_PASSWORD=secret
                        - POSTGRES_DB=sevima
                ports:
                        - "5342:5432"

        nginx:
                image: nginx:alpine
                container_name: nginx
                working_dir: /app
                volumes:
                        - .:/app
                ports:
                        - "3333:80"

        php-fpm:
                build: .
                container_name: php-fpm
                working_dir: /app
                volumes:
                        - .:/app

volumes:
        postgresdata:
